# Generated by Django 6.0.3 on 2026-03-20 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_delivery_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='has_delivery',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='has_pickup',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/logos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
