# Generated by Django 6.0.3 on 2026-03-20 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_shop_delivery_charge_remove_shop_has_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_open',
        ),
        migrations.AddField(
            model_name='shop',
            name='is_temporarily_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='temporary_close_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ShopSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_active', models.BooleanField(default=True)),
                ('morning_open', models.TimeField(blank=True, null=True)),
                ('morning_close', models.TimeField(blank=True, null=True)),
                ('afternoon_open', models.TimeField(blank=True, null=True)),
                ('afternoon_close', models.TimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shops.shop')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('shop', 'weekday')},
            },
        ),
    ]
