# Generated by Django 6.0.3 on 2026-03-20 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_shop_is_open_shop_is_temporarily_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='shop',
            name='has_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
