# Generated by Django 6.0.3 on 2026-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_delivery_charge_shop_has_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopschedule',
            name='close_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
