# Generated by Django 6.0.3 on 2026-04-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_shop_latitude_alter_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
    ]
