# Generated by Django 6.0.3 on 2026-03-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('shop_verified', 'Shop Verified'), ('shop_rejected', 'Shop Rejected'), ('order_status', 'Order Status'), ('b2b_order_placed', 'B2B Order Placed'), ('b2b_order_updated', 'B2B Order Updated')], max_length=50),
        ),
    ]
