# Generated by Django 6.0.3 on 2026-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('shop_verified', 'Shop Verified'), ('shop_rejected', 'Shop Rejected'), ('order_status', 'Order Status'), ('b2b_order_placed', 'B2B Order Placed'), ('b2b_order_updated', 'B2B Order Updated'), ('low_stock', 'Low Stock')], max_length=50),
        ),
    ]
