# Generated by Django 6.0.3 on 2026-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_cancel_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
