# Generated by Django 6.0.3 on 2026-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Shop Owner'), ('cold_storage', 'Cold Storage'), ('delivery_rider', 'Delivery Rider'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
