# Generated by Django 6.0.3 on 2026-04-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_confirm_orders',
            field=models.BooleanField(default=False),
        ),
    ]
