# Generated by Django 6.0.3 on 2026-03-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0010_alter_shop_latitude_alter_shop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_price', 'Pending Price'), ('priced', 'Priced'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_orders', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='B2BOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='b2b.b2border')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColdStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cold_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cold Storages',
            },
        ),
        migrations.AddField(
            model_name='b2border',
            name='cold_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_orders', to='b2b.coldstorage'),
        ),
        migrations.CreateModel(
            name='ColdStorageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('chicken', 'Chicken'), ('beef', 'Beef'), ('buffalo', 'Buffalo'), ('mutton', 'Mutton'), ('pork', 'Pork'), ('seafood', 'Seafood'), ('other', 'Other')], max_length=50)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_kg', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece')], default='kg', help_text='KG = price known upfront. Piece = price set after weighing.', max_length=10)),
                ('approx_weight_per_piece_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Approximate kg per piece. Shown to buyer as reference only. Supplier must weigh manually.', max_digits=6, null=True)),
                ('stock_pieces', models.PositiveIntegerField(blank=True, help_text='Available stock in pieces (used when unit_type=piece)', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cold_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='b2b.coldstorage')),
            ],
        ),
        migrations.CreateModel(
            name='B2BOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece')], default='kg', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Filled by supplier after weighing (piece orders only)', max_digits=10, null=True)),
                ('price_per_kg_final', models.DecimalField(blank=True, decimal_places=2, help_text='Final price per kg set by supplier (piece orders)', max_digits=10, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, help_text='NULL for piece orders until supplier prices them', max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b.b2border')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='b2b.coldstorageproduct')),
            ],
        ),
    ]
