# Generated by Django 6.0.3 on 2026-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldstorageproduct',
            name='min_order_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='coldstorageproduct',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coldstorageproduct',
            name='stock_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
