# Generated by Django 6.0.3 on 2026-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_alter_coldstorageproduct_min_order_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2borderitem',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
