# Generated by Django 6.0.3 on 2026-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_alter_b2borderitem_quantity_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2borderitem',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='coldstorageproduct',
            name='allowed_units',
            field=models.JSONField(default=list, help_text="['kg'], ['piece'], or ['kg','piece']"),
        ),
    ]
