# Generated by Django 6.0.3 on 2026-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_remove_b2borderitem_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borderitem',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece')], default='kg', max_length=10),
        ),
    ]
