# Generated by Django 6.0.3 on 2026-04-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0005_b2borderitem_unit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2border',
            options={'ordering': ['-created_at']},
        ),
    ]
