# Generated by Django 6.0.3 on 2026-04-03 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0007_b2border_is_paid_b2border_payment_type_ledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2border',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='b2border',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2border',
            name='order_source',
            field=models.CharField(choices=[('app', 'App'), ('phone', 'Phone'), ('walkin', 'Walk-in')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='b2border',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
