# Generated by Django 6.0.3 on 2026-04-03 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0008_remove_b2border_is_paid_b2border_collected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2border',
            name='collected_by',
        ),
        migrations.AddField(
            model_name='b2border',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
