# Generated by Django 6.0.3 on 2026-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_remove_b2border_collected_by_b2border_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldstorageproduct',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
