# Generated by Django 6.0.3 on 2026-04-04 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0010_coldstorageproduct_low_stock_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='weighted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighted_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
